version: '3.1'
services:
  stats-server:
    build: statistics_server/ewm-service
    image: statistic_service_image
    container_name: ewm-statistic-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    volumes:
      - /var/lib/postgresql/postgres/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

      #ewm-service:
      #ports:
      #- "8080:8080"

    #ewm-db:
    #image: postgres:14-alpine